name              'mariadb-enterprise'
maintainer        'MariaDB Corporation'
maintainer_email  'Andrey.Kuznetsov@mariadb.com'
license           'Apache 2.0'
description       'MariaDB Enterprise Chef Cookbook'
version           '0.0.9'
recipe            'install', 'Install MariaDB Enterprise Server'
recipe            'uninstall', 'Uninstall MariaDB Enterprise Server'
recipe            'purge', 'Uninstall MariaDB Enterprise Server and remove all data and configuration files'
recipe            'start', 'Create new instance of service and start it'
recipe            'stop', 'Create new instance of service and start it'
recipe            'install_backuper', 'Install backuper package'
recipe            'uninstall_backuper', 'Uninstall backuper package'
recipe            'backup', 'Create backup'
recipe            'restore', 'Restore backup'

supports          'redhat'
supports          'centos'
supports          'fedora'
supports          'debian'
supports          'ubuntu'
supports          'suse'

